import { Inter } from "next/font/google";
import "./globals.css";
import {EntitiesProvider} from "./_components/EntitiesProvider"
import SideBar from "./_components/Sidebar";
import { Toaster } from 'react-hot-toast';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <EntitiesProvider>
        <body className={inter.className}>
          <Toaster />
          <SideBar/>
          {children}
        </body>
      </EntitiesProvider>
      
    </html>
  );
}
